# Generated by Django 5.2.8 on 2025-11-22 16:30

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('summary', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('preview_rows', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
    ]
